version: '3'

services:
  servicea:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  serviceb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
